#!/bin/bash
# version 1.0
# https://github.com/ssbarnea/keytool-trust
REMHOST=$1
if [ -z "$REMHOST" ]; then
    echo "ERROR: Please specify the server name to import the certificatin from, eventually followed by the port number, if other than 443."
    exit 1
fi

if [ -n "${3}" ]; then
    declare -a CACERTS=("${3}")
else
    declare -a CACERTS=( \
        "/usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts" \
        "/usr/lib/jvm/java-7-oracle/jre/lib/security/cacerts" \
    )
fi

REMPORT=${2:-443}
KEYSTORE_PASS=changeit
KEYTOOL="$(which keytool)"
TARGET="${REMHOST}:${REMPORT}"
STDOUT="$(pwd)/$(basename "${0}").stdout"
STDERR="$(pwd)/$(basename "${0}").stderr"
for CACERT in "${CACERTS[@]}"; do
    if [ ! -e "$CACERT" ]; then
        echo "--- ${CACERT} not found!" 1>&2
        continue
    else
        echo "--- Attempting to add cert of ${TARGET} to ${CACERT}"
    fi

    rm -f "${TARGET}.pem" "${STDOUT}" "${STDERR}"
    if ! openssl s_client -connect "${TARGET}" 1>"${STDOUT}" 2>"${STDERR}" </dev/null; then
        cat "${STDOUT}"
        cat "${STDERR}"
        continue
    fi

    if ! sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' <"${STDOUT}" > "$(pwd)/${TARGET}.pem"; then
        echo "ERROR: Unable to extract the certificate from ${TARGET} ($?)"
        cat "${STDERR}"
	continue
    fi

    if $KEYTOOL -list -storepass ${KEYSTORE_PASS} -alias "${TARGET}" -keystore "$CACERT" >/dev/null; then
        echo "Key of ${TARGET} already found in ${CACERT}, skipping it."
    else
        $KEYTOOL -import -trustcacerts -noprompt -keystore "$CACERT" -storepass ${KEYSTORE_PASS} -alias "${TARGET}" -file "${TARGET}.pem"
    fi
done
